# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: andrei-florian-bratila-web CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Crear archivo .env.local con las variables y secrets
      - name: Crear archivo .env.local
        run: |
          echo "EMAIL=${{ vars.NEXT_PUBLIC_EMAIL }}" >> .env.local
          echo "GITHUB_URL=${{ vars.NEXT_PUBLIC_GUITHUB_URL }}" >> .env.local
          echo "LINKEDIN_URL=${{ vars.NEXT_PUBLIC_LINKEDIN_URL }}" >> .env.local
          echo "PHONE=${{ vars.NEXT_PUBLIC_PHONE }}" >> .env.local
          echo "X_URL=${{ vars.NEXT_PUBLIC_X_URL }}" >> .env.local
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env.local

      - run: npm i
      - run: npm run build --if-present
      - run: pm2 reload andrei-florian-bratila-web
